/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import models.Usuario;
import services.AuthService;

/**
 *
 * @author victor.ananias
 */
public class Menu extends javax.swing.JFrame {
    
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.verificaTipoUsuario();
        this.setLogin();
        
    }
    
    private void setLogin(){
        jLabelNomeUsuaro.setText(AuthService.getUser().getNome());
    }
    
    private void verificaTipoUsuario(){
        if (AuthService.getUser().getTipo().equals("Usuário")){
            jBtUsuarios.setVisible(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtVenda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBtHistorico = new javax.swing.JButton();
        jBtUsuarios = new javax.swing.JButton();
        jBtEstoque = new javax.swing.JButton();
        jLabelNomeUsuaro = new javax.swing.JLabel();
        jBtSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 600));

        jBtVenda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtVenda.setText("Vendas");
        jBtVenda.setPreferredSize(new java.awt.Dimension(200, 100));
        jBtVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtVendaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Menu");

        jBtHistorico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtHistorico.setText("Histórico");
        jBtHistorico.setPreferredSize(new java.awt.Dimension(200, 100));
        jBtHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtHistoricoActionPerformed(evt);
            }
        });

        jBtUsuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtUsuarios.setText("Usuários");
        jBtUsuarios.setPreferredSize(new java.awt.Dimension(200, 100));
        jBtUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtUsuariosActionPerformed(evt);
            }
        });

        jBtEstoque.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtEstoque.setText("Estoque");
        jBtEstoque.setPreferredSize(new java.awt.Dimension(200, 100));
        jBtEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtEstoqueActionPerformed(evt);
            }
        });

        jLabelNomeUsuaro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jBtSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtSair.setForeground(new java.awt.Color(0, 153, 204));
        jBtSair.setText("Sair");
        jBtSair.setBorderPainted(false);
        jBtSair.setContentAreaFilled(false);
        jBtSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtSairMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtSairMouseEntered(evt);
            }
        });
        jBtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(521, 521, 521)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabelNomeUsuaro, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addComponent(jBtVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jBtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(193, 193, 193))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelNomeUsuaro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)))
                .addGap(146, 146, 146)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtHistorico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(51, 51, 51)
                .addComponent(jBtUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtVendaActionPerformed
        Vendas v = new Vendas();
        v.setVisible(true);
        Menu.this.dispose();
    }//GEN-LAST:event_jBtVendaActionPerformed

    private void jBtEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtEstoqueActionPerformed
        Estoque e = new Estoque();
        e.setVisible(true);
        Menu.this.dispose();
    }//GEN-LAST:event_jBtEstoqueActionPerformed

    private void jBtUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtUsuariosActionPerformed
        Usuarios u = new Usuarios();
        u.setVisible(true);
        Menu.this.dispose();
    }//GEN-LAST:event_jBtUsuariosActionPerformed

    private void jBtHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtHistoricoActionPerformed
        VendasHistorico h = new VendasHistorico();
        h.setVisible(true);
        Menu.this.dispose();
    }//GEN-LAST:event_jBtHistoricoActionPerformed

    private void jBtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSairActionPerformed
        new Login().setVisible(true);
        Menu.this.dispose();
        AuthService.setUser(new Usuario());
    }//GEN-LAST:event_jBtSairActionPerformed

    private void jBtSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtSairMouseEntered
        jBtSair.setForeground(java.awt.Color.red);
    }//GEN-LAST:event_jBtSairMouseEntered

    private void jBtSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtSairMouseExited
        jBtSair.setForeground(new java.awt.Color(0, 153, 204));
    }//GEN-LAST:event_jBtSairMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtEstoque;
    private javax.swing.JButton jBtHistorico;
    private javax.swing.JButton jBtSair;
    private javax.swing.JButton jBtUsuarios;
    private javax.swing.JButton jBtVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNomeUsuaro;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
