
package views;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import helpers.CaracteresHelper;
import controllers.ProdutosController;
import controllers.VendasController;
import models.Produto;
import models.Venda;

public class Vendas extends javax.swing.JFrame {
    ArrayList<Produto> produtos = new ArrayList<>();
    private int linhaProdutoTbVendas = -1;
    private int linhaProdutoTbprodutos = -1;

    DefaultTableModel modeloTabelaCarrinho = new DefaultTableModel(new Object[][] {},
            new Object[] { "Código", "Produto", "Quantidade", "Preço" }) {
        boolean[] canEdit = new boolean[] { false, false, false, false, false, false };

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit[columnIndex];
        }
    };
    DefaultTableModel modeloTabelaProdutos = new DefaultTableModel(new Object[][] {},
            new Object[] { "Código", "Produto", "Em Estoque", "Preço Unidade" }) {
        boolean[] canEdit = new boolean[] { false, false, false, false, false, false };

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit[columnIndex];
        }
    };

    /**
     * Creates new form Tela1
     */
    public Vendas() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.geraTabelaProdutos();
        this.setTotal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jTextPesquisa = new javax.swing.JTextField();
        jBtAdicionar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTbVenda = new javax.swing.JTable();
        jBtSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbProd = new javax.swing.JTable();
        jBtRemover = new javax.swing.JButton();
        jBtLimparCarrinho = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBtMenu = new javax.swing.JButton();
        jLabelTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBtLimparPesquisar = new javax.swing.JButton();
        jTextQntProd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vendas");

        jLayeredPane1.setBackground(new java.awt.Color(254, 254, 254));
        jLayeredPane1.setOpaque(true);
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1100, 600));

        jTextPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPesquisaKeyTyped(evt);
            }

            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextPesquisaKeyPressed(evt);
            }
        });

        jBtAdicionar.setText("+");
        jBtAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAdicionarActionPerformed(evt);
            }
        });

        jTbVenda.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

        }, new String[] { "Código", "Produto", "Quantidade", "Preço" }) {
            Class[] types = new Class[] { java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class };
            boolean[] canEdit = new boolean[] { false, false, false, false };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTbVenda.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTbVenda);
        if (jTbVenda.getColumnModel().getColumnCount() > 0) {
            jTbVenda.getColumnModel().getColumn(0).setResizable(false);
            jTbVenda.getColumnModel().getColumn(1).setResizable(false);
            jTbVenda.getColumnModel().getColumn(2).setResizable(false);
            jTbVenda.getColumnModel().getColumn(3).setResizable(false);
        }

        jBtSalvar.setText("Salvar");
        jBtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSalvarActionPerformed(evt);
            }
        });

        jTbProd.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

        }, new String[] { "Código", "Produto", "Em Estoque", "Preço Unidade" }) {
            Class[] types = new Class[] { java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class };
            boolean[] canEdit = new boolean[] { false, false, false, false };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTbProd.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTbProd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTbProd.setMaximumSize(new java.awt.Dimension(202, 220));
        jTbProd.setMinimumSize(new java.awt.Dimension(202, 220));
        jTbProd.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTbProd);

        jBtRemover.setText("-");
        jBtRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtRemoverActionPerformed(evt);
            }
        });

        jBtLimparCarrinho.setText("Limpar");
        jBtLimparCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtLimparCarrinhoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Qnt:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Vendas");

        jBtMenu.setText("Menu");
        jBtMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtMenuActionPerformed(evt);
            }
        });

        jLabelTotal.setBackground(java.awt.Color.white);
        jLabelTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTotal.setText("  Total: R$");
        jLabelTotal.setBorder(new javax.swing.border.LineBorder(java.awt.Color.lightGray, 1, true));
        jLabelTotal.setOpaque(true);

        jLabel1.setText("Pesquisar:");

        jBtLimparPesquisar.setText("Limpar");
        jBtLimparPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtLimparPesquisarActionPerformed(evt);
            }
        });

        jTextQntProd.setText("1");
        jTextQntProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextQntProdKeyTyped(evt);
            }
        });

        jLayeredPane1.setLayer(jTextPesquisa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jBtAdicionar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jBtSalvar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jBtRemover, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jBtLimparCarrinho, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jBtMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabelTotal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jBtLimparPesquisar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextQntProd, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(jLayeredPane1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup().addGroup(jLayeredPane1Layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane1Layout.createSequentialGroup().addGap(24, 24, 24)
                                .addGroup(jLayeredPane1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10).addComponent(jBtLimparPesquisar))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jLayeredPane1Layout.createSequentialGroup().addContainerGap().addComponent(jBtMenu,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jLayeredPane1Layout.createSequentialGroup().addGap(35, 35, 35)
                                        .addGroup(jLayeredPane1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                                        .addComponent(jLabel2)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jTextQntProd))
                                                .addComponent(jBtAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(25, 25, 25)
                                        .addGroup(jLayeredPane1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 182,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                                        .addComponent(jBtLimparCarrinho,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 89,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(43, 43, 43).addComponent(jBtRemover,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 89,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jLayeredPane1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jBtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jScrollPane2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 460,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jLayeredPane1Layout.createSequentialGroup().addGap(13, 13, 13)
                                        .addComponent(jLabel3)))
                        .addContainerGap(13, Short.MAX_VALUE)));
        jLayeredPane1Layout.setVerticalGroup(jLayeredPane1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup().addGap(41, 41, 41).addComponent(jLabel3)
                        .addGap(108, 108, 108)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2).addComponent(jTextQntProd,
                                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18).addComponent(jBtAdicionar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap(143, Short.MAX_VALUE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBtLimparPesquisar).addComponent(jLabelTotal,
                                        javax.swing.GroupLayout.PREFERRED_SIZE, 23,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jLayeredPane1Layout.createSequentialGroup().addGap(6, 6, 6).addComponent(
                                        jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBtLimparCarrinho).addComponent(jBtRemover))
                        .addGap(82, 82, 82)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBtMenu).addComponent(jBtSalvar))
                        .addContainerGap()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geraTabelaProdutos() {
        try {
            produtos = new ProdutosController().buscarProdutos();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao buscar produtos.");
        }
        
        for (int i = 0; i < produtos.size(); i++) {
            modeloTabelaProdutos.addRow(new String[]{
                String.valueOf(produtos.get(i).getId()),
                String.valueOf(produtos.get(i).getNome()),
                String.valueOf(produtos.get(i).getQuantidade()),
                String.valueOf(CaracteresHelper.addMascaraMonetaria(produtos.get(i).getValor()))});
        }

        jTbProd.setModel(modeloTabelaProdutos);
    }
    
    private void setTotal(){
        CaracteresHelper caracteres = new CaracteresHelper();
        double total = 0;
        for(int contador =0;contador<jTbVenda.getRowCount();contador++){
            total = total + caracteres.rmMascaraMonetaria(jTbVenda.getValueAt(contador,3).toString());
        }
        jLabelTotal.setText("  Total: "+caracteres.addMascaraMonetaria(total));
    }
    
    private void procurarLinha(String palavra){
        
        for(int i=0; i< jTbProd.getRowCount();i++){
            String codProd = jTbProd.getValueAt(i, 1).toString();
            
            if(codProd.contains(palavra)){
                jTbProd.setRowSelectionInterval(i,i);
                break;
            }
            
        }
    }
    
    private boolean estoqueEstaVazio(){
        return (jTbProd.getValueAt(
                jTbProd.getSelectedRow(), 2).toString()).equals("1");
    }
    
    private int verificaQuantidade() {
        int opcao = 0;
        int quantidadeEscolhida;
        
        int codigoProduto = Integer.parseInt(
                jTbProd.getValueAt(jTbProd.getSelectedRow(), 0).toString());

        int quantidadeProduto = Integer.parseInt(
            jTbProd.getValueAt(jTbProd.getSelectedRow(), 2).toString());

        quantidadeEscolhida = Integer.parseInt(jTextQntProd.getText());
        
        if (quantidadeEscolhida > quantidadeProduto) {
            opcao = 0;
            //se tem ao menos 1 linha
        } else if (jTbVenda.getRowCount() > 0) {
            this.linhaProdutoTbVendas = linhaTabelaVendas();
            
            if(linhaProdutoTbVendas != -1){
                int quantidadeCarrinho = Integer.parseInt(
                        jTbVenda.getValueAt(linhaTabelaVendas(), 2).toString());
                
                if(quantidadeCarrinho + quantidadeEscolhida > quantidadeProduto){
                    opcao = 0;
                } else{
                    opcao = 2;
                }
            }
            //se a table tem mais de 1 linha mas nao contem
            else{
                opcao = 1;
            }
        }
        else {
            opcao = 1;
        }

        return opcao;
    }
    
    private int linhaTabelaVendas(){
        int testador = -1;
        int contador;
        
        for (contador = 0; contador < jTbVenda.getRowCount(); contador++) {
            Object linhaTbProd = jTbProd.getValueAt(jTbProd.getSelectedRow(), 0);
            Object linhaTbVenda = jTbVenda.getValueAt(contador, 0);
            
            if (linhaTbProd == linhaTbVenda) {
                testador = contador;
                break;
            }
        }
        return testador;
    }
    
    private void limpaTabela(){
        modeloTabelaCarrinho.setNumRows(0);
        modeloTabelaProdutos.setNumRows(0);
    }
    
    private void linhaTabelaProdutos(){
        for (int i = 0; i < jTbProd.getRowCount(); i++) {
            Object linhaTbProd = jTbProd.getValueAt(i, 0);
            Object linhaTbVenda = jTbVenda.getValueAt(jTbVenda.getSelectedRow(), 0);
            if (linhaTbProd == linhaTbVenda) {
                this.linhaProdutoTbprodutos = i;
                break;
            }
        }
    }
    
    private void adicionaTbVenda(){
        double valor_produto = CaracteresHelper.rmMascaraMonetaria(
                jTbProd.getValueAt(jTbProd.getSelectedRow(), 3).toString());
        int quantidade_produto = Integer.parseInt(jTextQntProd.getText());
        double valor_total = valor_produto*quantidade_produto;

        String codigo_produto = (String) jTbProd.getValueAt(jTbProd.getSelectedRow(),0);
        String nome_produto = (String) jTbProd.getValueAt(jTbProd.getSelectedRow(),1);
        String valorConvertido = CaracteresHelper.addMascaraMonetaria(valor_total);

        modeloTabelaCarrinho.addRow(new String[]{
            codigo_produto,
            nome_produto,
            String.valueOf(quantidade_produto),
            valorConvertido});

        jTbVenda.setModel(modeloTabelaCarrinho);
    }
    
    private void atualizaTbVenda(){
        double valor_produto = CaracteresHelper.rmMascaraMonetaria(jTbProd.getValueAt(jTbProd.getSelectedRow(),3).toString());
        int quantidadeSelecionada = Integer.parseInt(jTextQntProd.getText());
        int quantidade_produto = Integer.parseInt(jTbVenda.getValueAt(this.linhaProdutoTbVendas, 2).toString());

        int novaQuantidade_produto =quantidadeSelecionada+quantidade_produto;

        double valor = valor_produto*novaQuantidade_produto;

        modeloTabelaCarrinho.setValueAt(novaQuantidade_produto, this.linhaProdutoTbVendas,2 );

        modeloTabelaCarrinho.setValueAt(CaracteresHelper.addMascaraMonetaria(valor), this.linhaProdutoTbVendas,3 );
        
    }
    
    private void atualizaTbProdutos(){
        int quantidadeSelecionada = Integer.parseInt(jTextQntProd.getText());
        int quantidade_produto = Integer.parseInt(jTbProd.getValueAt(jTbProd.getSelectedRow(), 2).toString());
        int novaQuantidade = quantidade_produto-quantidadeSelecionada;

        modeloTabelaProdutos.setValueAt(novaQuantidade, jTbProd.getSelectedRow() ,2 );
    }
    
    private void atualizaTbProdRemove(){
        this.linhaTabelaProdutos();
        int quantidade_produto = Integer.parseInt(jTbProd.getValueAt(this.linhaProdutoTbprodutos, 2).toString());
        int quntidade_produtoCarrinho = Integer.parseInt(jTbVenda.getValueAt(jTbVenda.getSelectedRow(), 2).toString());
        
        int novaQntP = quantidade_produto+quntidade_produtoCarrinho;

        modeloTabelaProdutos.setValueAt(novaQntP, this.linhaProdutoTbprodutos ,2 );
    }
    
    private void registrarVenda(){
        Venda venda = new Venda();
       
        for(int i = 0; i < jTbVenda.getRowCount(); i++){
            venda.addItem(
                Integer.parseInt(jTbVenda.getValueAt(i, 0).toString()), 
                Integer.parseInt(jTbVenda.getValueAt(i, 2).toString()), 
                CaracteresHelper.rmMascaraMonetaria(jTbVenda.getValueAt(i, 3).toString())
            );
        }

        try {
            new VendasController().registrarVenda(venda);

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Erro ao registrar venda.");
        }
        
        JOptionPane.showMessageDialog(null,"Venda registrada.");
   }
    
    
    private void jBtAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAdicionarActionPerformed
        if(jTbProd.getSelectedRow()>-1){
            if(jTextQntProd.getText()==null){
                JOptionPane.showMessageDialog(null, "Você não digitou uma quantidade");
            }
            else{
                switch (this.verificaQuantidade()){
                    case 0:
                        if (estoqueEstaVazio()){
                            JOptionPane.showMessageDialog(null, "Produto em falta");
                        } else{
                            JOptionPane.showMessageDialog(null, "Quantidade maior que estoque");
                        }
                        break;
                    case 1:
                        this.adicionaTbVenda();
                        this.atualizaTbProdutos();
                        break;
                    case 2:
                        this.atualizaTbVenda();
                        this.atualizaTbProdutos();
                        break;
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
        this.setTotal();
    }//GEN-LAST:event_jBtAdicionarActionPerformed

    private void jBtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSalvarActionPerformed
        if(jTbVenda.getRowCount() > 0){
            this.registrarVenda();
            this.limpaTabela();
            this.geraTabelaProdutos();
            this.setTotal();
        }
        else{
            JOptionPane.showMessageDialog(null, "O carrinho está vazio");
        }
    }//GEN-LAST:event_jBtSalvarActionPerformed

    private void jBtRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtRemoverActionPerformed
        if(jTbVenda.getSelectedRow() > -1){
            
            atualizaTbProdRemove();
            modeloTabelaCarrinho.removeRow(jTbVenda.getSelectedRow());
        } 
        this.setTotal();
    }//GEN-LAST:event_jBtRemoverActionPerformed

    private void jBtLimparCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtLimparCarrinhoActionPerformed
        this.limpaTabela();
        this.geraTabelaProdutos();
        this.setTotal();
    }//GEN-LAST:event_jBtLimparCarrinhoActionPerformed

    private void jBtMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtMenuActionPerformed
        Vendas.this.dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_jBtMenuActionPerformed

    private void jTextPesquisaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPesquisaKeyTyped
        procurarLinha(jTextPesquisa.getText());
    }//GEN-LAST:event_jTextPesquisaKeyTyped

    private void jTextPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPesquisaKeyPressed
        
    }//GEN-LAST:event_jTextPesquisaKeyPressed

    private void jBtLimparPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtLimparPesquisarActionPerformed
        jTextPesquisa.setText("");
    }//GEN-LAST:event_jBtLimparPesquisarActionPerformed

    private void jTextQntProdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextQntProdKeyTyped
        if(!(evt.getKeyChar()+"").matches("[0-9]")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextQntProdKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtAdicionar;
    private javax.swing.JButton jBtSalvar;
    private javax.swing.JButton jBtLimparCarrinho;
    private javax.swing.JButton jBtLimparPesquisar;
    private javax.swing.JButton jBtMenu;
    private javax.swing.JButton jBtRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTbProd;
    private javax.swing.JTable jTbVenda;
    private javax.swing.JTextField jTextPesquisa;
    private javax.swing.JTextField jTextQntProd;
    // End of variables declaration//GEN-END:variables
}
